
title: Curriculam Vitae - Dipan Roy
email: dipanroy@mindwebs.org
description: >- # this means to ignore newlines until "baseurl:"
  If Content is King, Design is Queen, then Development is the Kingdom. Without Kingdom, King and Queen are nothing!
  And I can help build your Empire!
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: dipanr29
github_username:  dipan29

# Build settings
theme: minima
plugins:
  - jekyll-feed
port: 80

# Exclude from processing.
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
    -  Readme.md
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
